// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ubacavnqzxnnmexfpxhj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InViYWNhdm5xenhubm1leGZweGhqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwMTM1OTcsImV4cCI6MjA3MjU4OTU5N30.CsirFmQuIIdykSY_WX8sgudCTSem_y4fc_kx7GZOBwc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});